(function(g){'use strict';var C=g.COD;
 function pair(a,b){return a.relations[b.id]}
 C.Diplomacy={init:function(civs){civs.forEach(function(a){civs.forEach(function(b){if(a!==b)a.relations[b.id]={value:0,state:'neutral',trust:50,treatyUntil:0,warSince:null}})})},
 memory:function(c,type,other,intensity,year,text){c.memories.push({type:type,other:other,intensity:intensity,year:year,text:text});if(c.memories.length>80)c.memories.shift()},
 war:function(sim,a,b){if(!a.alive||!b.alive)return false;var ar=pair(a,b),br=pair(b,a);if(ar.state==='war')return false;var broken=['alliance','pact'].indexOf(ar.state)>=0;ar.state=br.state='war';ar.value=br.value=Math.min(-55,ar.value);ar.warSince=br.warSince=sim.year;a.warWeariness+=2;b.warWeariness+=2;this.memory(a,broken?'brokenTreaty':'war',b.id,broken?90:55,sim.year,'Guerra contra '+b.name);this.memory(b,broken?'betrayal':'war',a.id,broken?100:55,sim.year,'Guerra iniciada por '+a.name);sim.log('war',[a.id,b.id],a.name+' declarou guerra a '+b.name+'.',3);return true},
 peace:function(sim,a,b){var ar=pair(a,b),br=pair(b,a);if(ar.state!=='war')return false;ar.state=br.state='truce';ar.treatyUntil=br.treatyUntil=sim.year+12;ar.warSince=br.warSince=null;sim.log('treaty',[a.id,b.id],a.name+' e '+b.name+' assinaram uma trégua.',2);return true},
 tick:function(sim){sim.civs.forEach(function(a){a.memories.forEach(function(m){m.intensity*=m.type==='betrayal'?.992:.975});a.memories=a.memories.filter(function(m){return m.intensity>1});sim.civs.forEach(function(b){if(a.id>=b.id||!a.alive||!b.alive)return;var ar=pair(a,b),br=pair(b,a),mem=a.memories.filter(function(m){return m.other===b.id}).reduce(function(s,m){return s+(m.type==='trade'||m.type==='aid'?m.intensity:-m.intensity)},0);ar.value=Math.max(-100,Math.min(100,ar.value+Math.sign(-mem-ar.value)*.08));br.value=ar.value;if(ar.state==='truce'&&sim.year>=ar.treatyUntil)ar.state=br.state='neutral';if(ar.state!=='war'&&sim.rng.chance(.012)){var surplus=a.stocks.food-180,need=140-b.stocks.food;if(surplus>30&&need>0&&ar.value>-35){var q=Math.min(30,surplus,need);a.stocks.food-=q;b.stocks.food+=q;b.stocks.gold=Math.max(0,b.stocks.gold-q*.35);a.stocks.gold+=q*.35;ar.value=br.value=Math.min(100,ar.value+3);C.Diplomacy.memory(a,'trade',b.id,12,sim.year,'Comércio lucrativo');sim.log('trade',[a.id,b.id],a.name+' vendeu alimentos a '+b.name+'.',1)}}if(ar.state==='neutral'&&ar.value>35&&sim.rng.chance(.02)){ar.state=br.state='trade';sim.log('treaty',[a.id,b.id],a.name+' e '+b.name+' abriram comércio.',1)}else if(ar.state==='trade'&&ar.value>58&&sim.rng.chance(.015)){ar.state=br.state='pact';ar.treatyUntil=br.treatyUntil=sim.year+25;sim.log('treaty',[a.id,b.id],a.name+' e '+b.name+' firmaram pacto.',2)}else if(ar.state==='pact'&&ar.value>76&&sim.rng.chance(.012)){ar.state=br.state='alliance';sim.log('alliance',[a.id,b.id],a.name+' e '+b.name+' formaram uma aliança.',3)}})})}
 };
})(window);
